# Generated by Django 3.2.9 on 2022-02-01 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profil_img_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('follow', models.ManyToManyField(related_name='_users_user_follow_+', to='users.User')),
            ],
        ),
    ]
