# Generated by Django 3.2.9 on 2022-02-01 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric', regex="^[A-Za-zÀ-ÖØ-öø-ÿ'\\-\\s]{0,255}$")]),
        ),
    ]
