# Generated by Django 3.2.9 on 2021-12-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_user_tweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tweets',
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='crud.user'),
        ),
    ]
